# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  neovim = {
    pname = "neovim";
    version = "94677318655eb803fccef4409834b6b77e11282a";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "94677318655eb803fccef4409834b6b77e11282a";
      fetchSubmodules = false;
      sha256 = "sha256-b2Xk0g8JfH3+X7gwCf/3JhEJjOyDeZpD6Ur2aL98o1A=";
    };
    date = "2025-08-21";
  };
}
