# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cchook = {
    pname = "cchook";
    version = "a87a9dc93ce2c088f7b3d5d8de410365c7d43ed3";
    src = fetchFromGitHub {
      owner = "syou6162";
      repo = "cchook";
      rev = "a87a9dc93ce2c088f7b3d5d8de410365c7d43ed3";
      fetchSubmodules = false;
      sha256 = "sha256-Fwx4dipTk9H+P/dNOGqjF4p/nhvR7zv9eD6n6RVnPOc=";
    };
    date = "2025-09-06";
  };
  k1Low-deck = {
    pname = "k1Low-deck";
    version = "f2f1fef8f7028ac1d723d5aebd53468a9e04f130";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "deck";
      rev = "f2f1fef8f7028ac1d723d5aebd53468a9e04f130";
      fetchSubmodules = false;
      sha256 = "sha256-kWQPB+sIpFFWgwdhayQeq5V0+b6HzsqP838YsrFmq/I=";
    };
    date = "2025-10-02";
  };
  neovim = {
    pname = "neovim";
    version = "a65202e6bd17f5daffaa2d2673128e6fc7b48d5d";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "a65202e6bd17f5daffaa2d2673128e6fc7b48d5d";
      fetchSubmodules = false;
      sha256 = "sha256-yza3hsg7qG1d0yU3RGIOrrxzbKSjJrkpGOxKgHoEtyA=";
    };
    date = "2025-10-13";
  };
  vim = {
    pname = "vim";
    version = "c58f91c035db09358c282f2a908e2aea4287785e";
    src = fetchFromGitHub {
      owner = "vim";
      repo = "vim";
      rev = "c58f91c035db09358c282f2a908e2aea4287785e";
      fetchSubmodules = false;
      sha256 = "sha256-IXO2zRR4PLFxErjBpgCGkZr9/zKJy4AQ9ECzQ6tVvWQ=";
    };
    date = "2025-10-12";
  };
}
