# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cchook = {
    pname = "cchook";
    version = "2d59b93c600a4651c2828e4bf06f2693799eefdc";
    src = fetchFromGitHub {
      owner = "syou6162";
      repo = "cchook";
      rev = "2d59b93c600a4651c2828e4bf06f2693799eefdc";
      fetchSubmodules = false;
      sha256 = "sha256-BVm4oTIFsW8P3gWKbgBzCWTgrFTeDOnZ09bSAuHBtvM=";
    };
    date = "2026-04-11";
  };
  deno-overlay = {
    pname = "deno-overlay";
    version = "d4d65b2070942ccb8f36329a380e720572d6a434";
    src = fetchFromGitHub {
      owner = "haruki7049";
      repo = "deno-overlay";
      rev = "d4d65b2070942ccb8f36329a380e720572d6a434";
      fetchSubmodules = false;
      sha256 = "sha256-b1cDSA3NMKNKn19rvKth9z4ZMSh/Ot+b9YvUTnVu5wI=";
    };
    date = "2026-07-02";
  };
  k1Low-deck = {
    pname = "k1Low-deck";
    version = "e5d55df7f909972e76553549a0c706495f671e91";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "deck";
      rev = "e5d55df7f909972e76553549a0c706495f671e91";
      fetchSubmodules = false;
      sha256 = "sha256-Pv36kaaOTdAP02cH+h+gLR+cjIDaqAg2XnNEvsIpeaY=";
    };
    date = "2026-06-22";
  };
  laminate = {
    pname = "laminate";
    version = "1580b51f607bca5ded2a0d1d9e9ae1e156fb5eb9";
    src = fetchFromGitHub {
      owner = "Songmu";
      repo = "laminate";
      rev = "1580b51f607bca5ded2a0d1d9e9ae1e156fb5eb9";
      fetchSubmodules = false;
      sha256 = "sha256-KoSE73ka7odmA29fpYC7iKCE3glMYWL0Q7AZOX5vAYU=";
    };
    date = "2025-09-05";
  };
  pict = {
    pname = "pict";
    version = "a096eaf237abcc50fdc48b0dc2d468622083a33d";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "pict";
      rev = "a096eaf237abcc50fdc48b0dc2d468622083a33d";
      fetchSubmodules = false;
      sha256 = "sha256-GS2/IhCAtgT79Lk2v6xxGx6WVzrbxUXtQIYPeRyzyyI=";
    };
    date = "2026-05-13";
  };
  roots = {
    pname = "roots";
    version = "v0.4.1";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "roots";
      rev = "v0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-ACMRfWY/lhc3C/KVhuUyS1rgkSHGWPxZrmYt+pXupJI=";
    };
  };
  safe-chain = {
    pname = "safe-chain";
    version = "1.5.12";
    src = fetchFromGitHub {
      owner = "AikidoSec";
      repo = "safe-chain";
      rev = "1.5.12";
      fetchSubmodules = false;
      sha256 = "sha256-rz8O+FxY3gHTmoYeisvS2cucFQe7sWwsEWpSHIT0oqA=";
    };
  };
  secretlint = {
    pname = "secretlint";
    version = "v13.0.2";
    src = fetchFromGitHub {
      owner = "secretlint";
      repo = "secretlint";
      rev = "v13.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-jnhTmJt0muuupQ9jDyIeyXFCNDWi49rqSa9ki7PvHhs=";
    };
  };
}
