name: Cachix Push

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: ubuntu-24.04-arm
            system: aarch64-linux
          - os: macos-latest
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build packages
        run: |
          nix build $(nix eval --json .#packages.${{ matrix.system }} --apply 'builtins.attrNames' | jq -r 'map(".#" + .) | join(" ")')
